[package]
name = "proctree-sys"
version = "0.1.0"
edition = "2018"
links = "proctree"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.53.1"
cc = { version = "1.0", features = ["parallel"] }

